version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./Web/:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql:5.7
    networks:
      - backend
    command: --init-file /data/application/beacon.sql
    volumes:
      - ./sql_dump/beacon.sql:/data/application/beacon.sql
    environment:
      MYSQL_DATABASE: beacon
      MYSQL_ROOT_PASSWORD: root

networks:
  frontend:
  backend:
