version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./Web/:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
      - steam_stuff
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql:5.7
    logging:
        driver: none
    networks:
      - backend
    command: --init-file /data/application/beacon.sql
    volumes:
      - ./sql_dump/beacon.sql:/data/application/beacon.sql
    environment:
      MYSQL_DATABASE: beacon
      MYSQL_ROOT_PASSWORD: root


  steam_stuff:
    volumes:
      - ./steam_stuff/:/home/steam/
    ports:
      - "27015:27015"
    build: './steam_docker'

networks:
  frontend:
  backend:
